# 应用配置
app:
  name: "贴吧系统"
  version: "1.0.0"
  port: 8080
  mode: "debug"

# 数据库配置
database:
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "password"
    database: "tieba_system"
    charset: "utf8mb4"
    max_idle_conns: 10
    max_open_conns: 100

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0

# JWT配置
jwt:
  secret: "tieba-system-secret-key"
  expire_hours: 24

# 日志配置
log:
  level: "info"
  path: "./logs"
  max_size: 100
  max_backups: 30
  max_age: 7